languages:
  - id: py3
    name: Python 3
    source: solution.py
    run:
      cmd: /usr/bin/python3
      args: ["{{source}}"]
      limits: { wall_time_s: 9, memory_kb: 102400, max_processes: 100 }
    smoke:
      cmd: /usr/bin/python3
      args: ["--version"]
      limits: { wall_time_s: 3, memory_kb: 102400, max_processes: 100 } 

  - id: cpp
    name: C++
    source: solution.cpp
    artifact: solution
    build:
      cmd: /usr/bin/g++
      args: ["{{flags}}", "-o", "{{artifact}}", "{{source}}"]
      limits: { wall_time_s: 3, memory_kb: 1048576, max_processes: 100 }
      flag_allowlist: ["-O0","-O1","-O2","-O3","-Wall","-Wextra","-std=*"]
    run:
      cmd: ./{{artifact}}
      limits: { wall_time_s: 3, memory_kb: 524288, max_processes: 64 }
    smoke:
      cmd: /usr/bin/g++
      args: ["--version"]
      limits: { wall_time_s: 3, memory_kb: 1048576, max_processes: 100 }

  - id: c
    name: c
    source: solution.c
    artifact: solution
    build:
      cmd: /usr/bin/gcc
      args: ["{{flags}}", "-o", "{{artifact}}", "{{source}}"]
      limits: { wall_time_s: 3, memory_kb: 1048576, max_processes: 100 }
      flag_allowlist: ["-O0","-O1","-O2","-O3","-Wall","-Wextra","-std=*"]
    run:
      cmd: ./{{artifact}}
      limits: { wall_time_s: 3, memory_kb: 524288, max_processes: 64 }
    smoke:
      cmd: /usr/bin/gcc
      args: ["--version"]
      limits: { wall_time_s: 3, memory_kb: 1048576, max_processes: 100 }

  - id: java
    name: Java
    source_filename_strategy: from_request
    artifact_filename_strategy: from_request  
    build:
      cmd: /usr/lib/jvm/java-17-openjdk-amd64/bin/javac
      args: ["{{flags}}", "{{source}}"]
      limits: { wall_time_s: 6, memory_kb: 1024000, max_processes: 100 }
    run:
      cmd: /usr/lib/jvm/java-17-openjdk-amd64/bin/java
      args: ["{{artifact}}"]
      limits: { wall_time_s: 6, memory_kb: 10240000, max_processes: 100 }
  
  - id: verilog
    name: Verilog
    source: solution.v
    artifact: solution
    build:
      cmd: /usr/bin/iverilog
      args: ["{{flags}}", "-o", "{{artifact}}", "{{source}}"]
      limits: { wall_time_s: 6, memory_kb: 1024000, max_processes: 100 }
      flag_allowlist: ["-full64","-debug","-O0","-O1","-O2","-O3"]
    run:
      cmd: ./{{artifact}}
      limits: { wall_time_s: 6, memory_kb: 10240000, max_processes: 100 }
    smoke:
      cmd: /usr/bin/iverilog
      args: ["-V"]
      limits: { wall_time_s: 3, memory_kb: 1048576, max_processes: 100 }

  - id: js
    name: JavaScript
    source: solution.js
    run:
      cmd: /usr/bin/node
      args: ["{{source}}"]
      limits: { wall_time_s: 9, memory_kb: 102400, max_processes: 100 }
    smoke:
      cmd: /usr/bin/node
      args: ["--version"]
      limits: { wall_time_s: 3, memory_kb: 102400, max_processes: 100 }

nsjail_flags: ["-Mo", 
    # "-Q", # Q is for really quite - only fatal stuff will be logged
    "-E", "PATH=/usr/local/bin:/usr/bin:/bin",
    "--chroot", "/",
    "-R", "/etc",
    "-T", "/tmp",
    "--cwd", "/app",
    "--log_fd" , "3", # To redirect logs
    "--use_cgroupv2",
    # "-v"
    ]
std_limit: 102400